### ISSUE TITLE
Oops! Something went wrong. mapit.js

### ISSUE THREAD

**Issue by sukar2019** [vdw/MapIt#3]
hey, guys about the problem of Oops! Something went wrong
[https://s15.postimg.org/eozvu0c63/Screen_Shot_2016_09_27_at_2_37_26_PM.png](url)
just you have to edit in file "jquery.mapit.js"
# HENT I REMOVE < FROM SCRIPT CUZ IT DOESN'T APPEAR IN PREVIEW

document.write('script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script');

with

document.write('script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&key=YOU_KEY_API&callback=initMap"></script');
That's all i hope it help you guys ^_^

**Comment by vdw** [comment]
Issues related to Google Maps API and its key are resolved at version [0.3.0](https://github.com/vdw/MapIt/tree/v0.3.0). Also [setup](https://github.com/vdw/MapIt/wiki/Setup) instructions are up to date.
